apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: "guest"
  password: "guest"
  uri: "amqp://guest:guest@rabbitmq:5672/"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
type: Opaque
stringData:
  POSTGRES_DB: auth_service
  POSTGRES_USER: auth_service
  POSTGRES_PASSWORD: change_me_in_production

---
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
type: Opaque
stringData:
  POSTGRES_DB: user_service
  POSTGRES_USER: user_service
  POSTGRES_PASSWORD: change_me_in_production

---
apiVersion: v1
kind: Secret
metadata:
  name: task-db-secret
type: Opaque
stringData:
  POSTGRES_DB: task_service
  POSTGRES_USER: task_service
  POSTGRES_PASSWORD: change_me_in_production

---
apiVersion: v1
kind: Secret
metadata:
  name: org-db-secret
type: Opaque
stringData:
  POSTGRES_DB: organization_service
  POSTGRES_USER: organization_service
  POSTGRES_PASSWORD: change_me_in_production

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
type: Opaque
stringData:
  admin-password: "change_me_in_production"
